### ISSUE TITLE
Support Pixi.js v7

### ISSUE THREAD

**Issue by milan-magyar** [Prozi/pixi-stats#1]
Hello @Prozi !

At first, thanks for this great tool, it helps a lot by working with Pixi.js!

I just saw that you added a strict v6.x check to the package.json. Do you plan to support v7 in the future?

Thanks!

**Comment by nenjack** [comment]
@milan-magyar thank you for using this one :)

you can try version 1.1.1 - I've bumped the dependency, and updated some other stuff and it seems to work

**Comment by milan-magyar** [comment]
Thanks @Prozi! It works perfectly with the newest Pixi version.

**Comment by nenjack** [comment]
> Thanks @Prozi! It works perfectly with the newest Pixi version.

actually please use v1.1.2 as it has Draw Calls and Texture Counter fixed

**Comment by nenjack** [comment]
cc @milan-magyar
