### ISSUE TITLE
Correctly support ESM

### ISSUE THREAD

**Issue by danrichman** [Prozi/pixi-stats#2]
Our Vite app was unable to work with this package. The dependency was loaded as a CommonJS module due to the presence of a `main:` field in the `package.json`, which points to ESM files. The `main:` field should point to a Common JS version of the files, but the syntax in them is ESM. This causes Vite to fail to load the files because it comes across that unexpected syntax.

See the Node documentation for the `"exports"`:
https://nodejs.org/api/packages.html#main-entry-point-export

**Comment by nenjack** [comment]
@danrichman please check v1.2.0 should be fine now

**Comment by nenjack** [comment]
v1.2.1 sorry there was a bug in not included "dist" folder in v1.2.0

**Comment by nenjack** [comment]
forgot to close this after implementing the fix, closing :)
